---
- name: Converge
  hosts: molecule
  gather_facts: true
  tasks:
    - name: Testing role install home PC
      ansible.builtin.include_role:
        name: jgirard.install_home_pc
        tasks_from: main.yml
